### ISSUE TITLE
Option to only reload preview on file save

### ISSUE THREAD

**Issue by Riveascore** [rafalou38/svelte-preview#5] opened 2021-11-18 01:37 UTC
It's frustrating to have the preview constantly change / blink as soon as you attempt to define a variable etc.

Would be nice to have a toggle for:
"Only reload preview on save"

Until then, this extension is "unusable" for me. I'll have to stick to web browser for now.

Not trying to be harsh, what you've built is incredible.

**Comment by rafalou38** [comment] 2021-11-18 06:26
Thanks for the support 😄

- A switch to reload only on save is easy to add, I'll add it soon
- until then you can use the `use rollup` switch that only reloads on save but is a bit slower
- I also plan to fix the blinking to give the feeling of instant changes

**Comment by rafalou38** [comment] 2021-11-19 10:52
Can you give more details about this blinking, is it the background color or the components of the preview that annoying you?
Can you share a screen record or reproducible example?

**Comment by rafalou38** [comment] 2021-11-19 11:21
In the last version (2.4.0) 
I added a switch to only reload preview on file save and did some improvements to make the blinking smaller

**Comment by rafalou38** [comment] 2021-12-01 20:45
Closing as this issue seems to be fixed

**Closed by rafalou38** 2021-12-01 20:45 UTC
Labels: enhancement
